version: 0.2
eb_codebuild_settings:
    CodeBuildServiceRole: role-name
    ComputeType: BUILD_GENERAL1_SMALL
    Image: aws/codebuild/nodejs:10.14.1
    Timeout: 30

phases:
    install:
        commands:
            - npm install
            - echo INSTALL completed on `date`
    build:
        commands:
            - echo BUILD started on `date`
            - echo `pwd`
            - npm run production
            - echo BUILD completed on `date`
artifacts:
    files:
        - '**/*'

cache:
    paths:
        - '/node_modules/*/**'
