version: '2'
services:

    web:
        image: venveo/baseimage:php7-apache-alpine
        ports:
            - 8000:80
        depends_on:
            - mysql-server
            - redis-server
        links:
            - mysql-server
            - redis-server
        cap_add:
          - SYS_TIME
          - SYS_NICE
        volumes:
            - ./vendor:/app/vendor
            - ./web:/app/web
            - ./plugins:/app/plugins
            - ./config:/app/config
            - ./modules:/app/modules
            - ./templates:/app/templates
            - ./.env:/app/.env
            - ./storage:/app/storage
        env_file: .env

    mysql-server:
        image: venveo/baseimage:5.7-mysql
        ports:
            - 3306:3306
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: SuperLongPassword!
            MYSQL_DATABASE: dev_craftcms
            MYSQL_PASSWORD: Password1!
            MYSQL_USER: craftcms
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"

    redis-server:
        image: redis:alpine
